[package]
name = "tempo-state-dump"

version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
# Workspace dependencies
alloy = { workspace = true, features = [
    "genesis",
    "network",
    "provider-http",
    "rand",
    "rpc-types",
    "signers",
    "signer-local",
] }
clap = { workspace = true, features = ["derive"] }
eyre.workspace = true
futures.workspace = true
indicatif.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true

# Bespoke dependencies
hex = "0.4"
rand = "0.9"
rand_08 = { package = "rand", version = "0.8" }
rand_distr = "0.5.1"
rayon = "1.10"
reth-db-common = { path = "../../../../oss/reth/crates/storage/db-common" }
